/**
 * The rendering budget, and the benchmark that reports against it.
 *
 * ## Why a budget exists at all
 *
 * These are animated by handing the browser a fresh SVG string each frame, and
 * `innerHTML` reparses and relays out the whole scene. Measured in Chromium
 * with layout forced:
 *
 *     iso-terrain   1190 elements  127KB   3.35ms avg   10.9ms worst
 *     flow-lines     595 elements  107KB   2.34ms avg    4.0ms worst
 *     truchet-arcs   198 elements   97KB   1.49ms avg    3.3ms worst
 *     contour         17 elements   12KB   0.34ms avg    0.6ms worst
 *
 * **Element count predicts the cost far better than byte count does.**
 * `truchet-arcs` is nearly as large as `flow-lines` in bytes and less than half
 * the cost, because it emits a third as many elements. So the budget is on
 * elements, and bytes are a secondary check for the data-URI path.
 *
 * ## Why density 1 and not the default
 *
 * `density` is a consumer-facing dial. A budget measured at the default is a
 * budget that does not hold, because nothing stops a caller asking for 1. The
 * worst case is the only case worth pinning.
 *
 * ## The report
 *
 *     BENCH_GRAPHICS=1 pnpm vitest run tests/graphics-budget.test.ts
 *
 * writes `docs/graphics-benchmark.md` — every generator, sorted by cost, with
 * `project()` timings alongside. The timings are reported and never asserted:
 * they are machine-dependent, and a test that fails on a busy laptop teaches
 * people to ignore it. Elements and bytes are deterministic, so those are the
 * ones with teeth.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { GENERATOR_LIST } from '../components/graphics/registry';
import type { GraphicParams } from '../components/graphics/types';
import { textSafeOpacity } from '../lib/graphicsLegibility';

/**
 * Elements a generator may emit at density 1.
 *
 * Set from measurement, not taste: at ~1200 elements a single tile costs most
 * of a 60fps frame budget on its own, and the median generator emits 270. 900
 * leaves the median untouched while bringing the eight outliers into a range
 * where two tiles can animate without contention.
 */
const ELEMENT_BUDGET = 900;

/** Raw SVG bytes at density 1. The data-URI path inflates this by roughly a third. */
const BYTE_BUDGET = 240_000;

function params(over: Partial<GraphicParams> = {}): GraphicParams {
  return {
    width: 1280,
    height: 720,
    seed: 7,
    accent: '#22d3ee',
    background: 'transparent',
    density: 1,
    opacity: 1,
    strokeWidth: 2,
    t: 0,
    occlusion: '#0a0a1a',
    disorder: 0,
    contrast: 1,
    originX: 0.5,
    originY: 0.5,
    ...over,
  };
}

const MARK = /<(path|circle|line|rect|polygon|polyline|ellipse)\b/g;

interface Row {
  name: string;
  els: number;
  kb: number;
  ms: number;
}

function measure(): Row[] {
  return GENERATOR_LIST.map((g) => {
    const p = params();
    const structure = g.sample(p);
    for (let i = 0; i < 3; i++) g.project(structure, p, i / 3);
    const N = 20;
    const t0 = performance.now();
    let svg = '';
    for (let i = 0; i < N; i++) svg = g.project(structure, p, i / N);
    const ms = (performance.now() - t0) / N;
    return {
      name: g.name,
      els: (svg.match(MARK) ?? []).length,
      kb: Math.round(svg.length / 1024),
      ms: Number(ms.toFixed(2)),
    };
  }).sort((a, b) => b.els - a.els);
}

describe('rendering budget', () => {
  const rows = measure();

  if (process.env.BENCH_GRAPHICS === '1') {
    const lines = [
      '# Graphics rendering benchmark',
      '',
      'Generated by `BENCH_GRAPHICS=1 pnpm vitest run tests/graphics-budget.test.ts`.',
      'Do not edit by hand.',
      '',
      'Measured at 1280x720, seed 7, **density 1** — the worst case a consumer can',
      'ask for. `ms` is `project()` alone, averaged over 20 frames, and is machine-',
      'dependent: it is reported for comparison between generators, never asserted.',
      '',
      'The cost that actually matters is not here, because it is not measurable in',
      'Node: `innerHTML` reparse and layout in the browser, which tracks element',
      'count. See the note at the top of the test.',
      '',
      `Budget: **${ELEMENT_BUDGET} elements**, **${BYTE_BUDGET / 1000}KB** raw SVG.`,
      '',
      'The last column is the highest global `opacity` at which the generator stays',
      'safe to put text over — see `docs/graphics-legibility.md`. At full weight',
      'these are artwork; as backdrops they are used dimmed, and this says how far.',
      '',
      '| Generator | Elements | KB | project() ms | text-safe opacity |',
      '| --- | ---: | ---: | ---: | ---: |',
      ...rows.map(
        (r) =>
          `| \`${r.name}\` | ${r.els} | ${r.kb} | ${r.ms} | ${textSafeOpacity(r.name).toFixed(2)} |`,
      ),
      '',
      `Median elements: **${[...rows].sort((a, b) => a.els - b.els)[Math.floor(rows.length / 2)].els}**. ` +
        `Total \`project()\` if every generator drew at once: **${rows.reduce((a, b) => a + b.ms, 0).toFixed(0)}ms**.`,
      '',
    ];
    writeFileSync(
      join(__dirname, '..', 'docs', 'graphics-benchmark.md'),
      `${lines.join('\n')}\n`,
    );
  }

  it.each(rows.map((r) => [r.name, r] as const))(
    '%s: stays within the element budget at density 1',
    (_name, r) => {
      expect(r.els).toBeLessThanOrEqual(ELEMENT_BUDGET);
    },
  );

  it.each(rows.map((r) => [r.name, r] as const))(
    '%s: stays within the byte budget at density 1',
    (_name, r) => {
      expect(r.kb * 1024).toBeLessThanOrEqual(BYTE_BUDGET);
    },
  );

  it('keeps the median generator well under budget', () => {
    // A budget every generator sits just under is a budget that has been tuned
    // to the code rather than the other way round. The median should have
    // headroom to spare.
    const median = [...rows].sort((a, b) => a.els - b.els)[
      Math.floor(rows.length / 2)
    ];
    expect(median.els).toBeLessThan(ELEMENT_BUDGET / 2);
  });
});
